services:
  db:
    image: postgres:15
    container_name: soavs_db
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    container_name: soavs_backend
    restart: always
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend:/app
      - ./.env:/app/.env
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
    depends_on:
      - db

  frontend:
    build: ./frontend-web
    container_name: soavs_frontend
    restart: always
    ports:
      - "5173:5173"
    volumes:
      - ./frontend-web:/app
      - /app/node_modules
    depends_on:
      - backend

volumes:
  postgres_data:
