# Generated by Django 6.0.5 on 2026-05-15 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0002_voterecord'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='position',
            options={'ordering': ['hierarchy_order', 'id']},
        ),
        migrations.AddField(
            model_name='candidate',
            name='course_and_year',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='candidate',
            name='platform_statement',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='position',
            name='hierarchy_order',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Partylist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partylists', to='elections.election')),
            ],
            options={
                'unique_together': {('election', 'name')},
            },
        ),
        migrations.AddField(
            model_name='candidate',
            name='partylist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidates', to='elections.partylist'),
        ),
    ]
